idf_component_register(
    SRCS
        "dali_ringbuf.c"
        "dali_phy.c"
        "dali_scheduler.c"
        "dali_protocol.c"
        "dali_input_device.c"
        "dali_input_poll.c"
        "dali_event.c"
        "dali_discovery.c"
        "dali_commissioning.c"
        "dali_lunatone.c"
        "dali_steinel.c"
        "dali_mapping.c"
        "dali_memory.c"
        "dali_gear_dt6.c"
        "dali_gear_dt8.c"
        "dali_input_config.c"
        "dali_control.c"
        "dali_dispatch.c"
        "dali_group_map.c"

    INCLUDE_DIRS "."
    REQUIRES
        driver
        esp_driver_gpio
        esp_driver_gptimer
        esp_timer
        freertos
)
