idf_component_register(
    SRCS
        "dali_ringbuf.c"
        "dali_phy.c"
        "dali_scheduler.c"
        "dali_protocol.c"
        "dali_lunatone.c"
        "dali_steinel.c"
        "dali_mapping.c"
        "dali_control.c"
        "dali_diag.c"
    INCLUDE_DIRS "."
    REQUIRES
        driver
        esp_driver_gpio
        esp_driver_gptimer
        esp_driver_uart
        esp_timer
        freertos
)
